import { Inter } from "next/font/google";

import "./globals.css";
import MainContent from "../components/RootLayout/MainContent";
import Footer from "../components/RootLayout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // todo
  title: "Weather App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContent>{children}</MainContent>
        <Footer copyYear={new Date().getFullYear().toString()} />
      </body>
    </html>
  );
}
